(add-to-list 'load-path (concat user-emacs-directory ".config"))
(require 'package)
(package-initialize)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(setq use-package-always-ensure t)
(require 'settings)
(require 'evilvim)
(global-set-key (kbd "C-c l") 'toggle-line-numbers)
